plugins {
    id 'com.android.application'
}

android {
    namespace 'com.nsd.geocraft'
    compileSdk 35

    defaultConfig {
        applicationId 'com.nsd.geocraft'
        minSdk 26
        targetSdk 35
        versionCode 4
        versionName '1.0.3'
    }

    signingConfigs {
        release {
            def keystorePath = System.getenv("GEOCRAFT_KEYSTORE_PATH")
            def storePassword = System.getenv("KEYSTORE_PASSWORD")
            def keyAlias = System.getenv("KEY_ALIAS")
            def keyPassword = System.getenv("KEY_PASSWORD")

            if (keystorePath && storePassword && keyAlias && keyPassword) {
                storeFile file(keystorePath)
                this.storePassword = storePassword
                this.keyAlias = keyAlias
                this.keyPassword = keyPassword
            }
        }
    }

    buildTypes {
        release {
            minifyEnabled false

            def hasReleaseKey =
                    System.getenv("GEOCRAFT_KEYSTORE_PATH") &&
                    System.getenv("KEYSTORE_PASSWORD") &&
                    System.getenv("KEY_ALIAS") &&
                    System.getenv("KEY_PASSWORD")

            signingConfig hasReleaseKey ? signingConfigs.release : signingConfigs.debug
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}
